### ISSUE TITLE
Add power up

### ISSUE THREAD

**Issue by Jflyer45** [Jflyer45/CIS122-Project#21]
Add atleast one power up, like seen in ep 22. Be creative and try to make some other power ups as well. When done, add your power ups to the prefab folder so that they can be used else where

**Comment by Madeline-Ellingson** [comment]
Added 3 Power Ups

Golden Pineapple
- Increases Jump Height
Golden Apple
- Increases Movement Speed
Super Banana
- Increases Both Movement Speed and Jump Height
